from dotenv import load_dotenv
from langchain_anthropic import ChatAnthropic
from tools.ticketmaster import search_ticketmaster_events
from tools.google_places import search_google_places_raw
from tools.eventbrite import search_eventbrite_events
from typing import Optional
from concurrent.futures import ThreadPoolExecutor
import os
import json
import logging

logger = logging.getLogger(__name__)

load_dotenv()

# ---- THE MODEL ----
# Haiku — ~4x faster than Sonnet for structured formatting tasks
llm = ChatAnthropic(
    model="claude-haiku-4-5-20251001",
    temperature=0,
    api_key=os.getenv("ANTHROPIC_API_KEY")
)

keywords_list = "sibling friendly, dog friendly, accessible, parking nearby, café on site, book in advance, free cancellation, outdoor, indoor, rainy day, sunny day, drop in, booking required, gift shop, picnic area, photography allowed"

def parse_response(response_text: str, activities_str: str, location: str) -> dict:
    """Parse Claude's JSON response, stripping any markdown fences."""
    try:
        cleaned = response_text.strip()
        if cleaned.startswith("```"):
            cleaned = cleaned.split("```")[1]
            if cleaned.startswith("json"):
                cleaned = cleaned[4:]
        return json.loads(cleaned.strip())
    except json.JSONDecodeError as e:
        logger.error(f"Failed to parse Claude JSON: {str(e)}")
        return {
            "search_summary": f"{activities_str} in {location}",
            "search_extended": False,
            "search_extended_message": None,
            "events": [],
            "venues": [],
            "error": "Sorry, something went wrong. Please try again."
        }

def inject_venue_photos(venues: list, photo_urls: dict[str, str]) -> list:
    """
    Inject photo URLs into venue results after Claude has formatted them.
    Claude doesn't generate image_url — we match by venue name and inject here.
    This saves ~400 output tokens per search, significantly speeding up Claude.
    """
    for venue in venues:
        name = venue.get("name", "")
        if name in photo_urls:
            venue["image_url"] = photo_urls[name]
        elif venue.get("image_url") is None:
            # Try partial name match for cases where Claude reformats the name slightly
            for photo_name, url in photo_urls.items():
                if photo_name.lower() in name.lower() or name.lower() in photo_name.lower():
                    venue["image_url"] = url
                    break
    return venues

# ---- VENUES SEARCH ----
# Calls Google Places only — fast with Haiku (~8-15 seconds)
# Photo URLs extracted in Python, not generated by Claude
def run_venues_search(
    activities: list[str],
    location: str,
    date: str,
    age_range: str,
    cost_range: str,
    vibes: list[str] = [],
    latitude: Optional[float] = None,
    longitude: Optional[float] = None,
    radius_miles: int = 5,
    free_text: Optional[str] = None
) -> dict:
    activities_str = ", ".join(activities) if activities else "family activities"

    # Call Google Places — get text for Claude AND photo URLs separately
    try:
        google_data, photo_urls = search_google_places_raw(
            query=activities_str,
            location=location,
            latitude=latitude,
            longitude=longitude,
            radius_miles=radius_miles
        )
    except Exception as e:
        logger.error(f"Google Places error: {str(e)}")
        google_data = "No results found."
        photo_urls = {}

    vibes_str = f"\nPrioritise results that are: {', '.join(vibes)}" if vibes else ""
    free_text_str = f"\nUser also searched for: \"{free_text}\"" if free_text and free_text.strip() else ""

    if latitude is not None and longitude is not None:
        radius_str = f"\nPrefer results within {radius_miles} miles of ({latitude:.4f}, {longitude:.4f}). If extending, set search_extended=true with a friendly message."
    else:
        radius_str = ""

    # Note: image_url is NOT in the prompt — we inject it after Claude responds
    # This saves ~400 output tokens and speeds up response significantly
    prompt = f"""Format this Google Places data into JSON for a family activities finder.

Search: {activities_str} in {location}, {date}, ages {age_range}, budget {cost_range}{vibes_str}{free_text_str}{radius_str}

GOOGLE PLACES DATA:
{google_data}

STRICT RULES:
1. VENUE = permanent place families visit year-round: museum, park, zoo, aquarium, gallery, theatre building, science centre, soft play, theme park. Even ticketed permanent attractions (London Eye, Madame Tussauds, Sea Life) are VENUES not events.
2. Only include venues matching: {activities_str}
3. Only use results from the data above — never add from your own knowledge
4. Return max 5 venues
5. cost: NEVER use null — use "Free", "From £X", or "Paid — check website"
6. directions_url: https://www.google.com/maps/dir/?api=1&destination=ADDRESS_URL_ENCODED
7. Keywords only from: {keywords_list}
8. image_url: always set to null (photos are added separately)

Return ONLY valid JSON:
{{
  "search_summary": "{activities_str} in {location}, {date}, Ages {age_range}, {cost_range}",
  "search_extended": false,
  "search_extended_message": null,
  "events": [],
  "venues": [
    {{
      "type": "venue",
      "name": "name",
      "image_url": null,
      "location": "full address",
      "latitude": 51.5074,
      "longitude": -0.1278,
      "opening_times": "Daily 10:00 AM - 5:00 PM",
      "age_range": "All ages",
      "cost": "Free",
      "is_free": true,
      "rating": 4.5,
      "keywords": ["indoor"],
      "description": "one sentence",
      "expanded_description": "2 sentences with practical family details",
      "website_url": "url or null",
      "directions_url": "https://www.google.com/maps/dir/?api=1&destination=ADDRESS"
    }}
  ]
}}"""

    response = llm.invoke(prompt)
    result = parse_response(response.content, activities_str, location)

    # Inject photo URLs after Claude responds — faster than asking Claude to generate them
    if result.get("venues"):
        result["venues"] = inject_venue_photos(result["venues"], photo_urls)

    return result


# ---- EVENTS SEARCH ----
# Calls Ticketmaster + Eventbrite in parallel
def run_events_search(
    activities: list[str],
    location: str,
    date: str,
    age_range: str,
    cost_range: str,
    vibes: list[str] = [],
    latitude: Optional[float] = None,
    longitude: Optional[float] = None,
    radius_miles: int = 5,
    free_text: Optional[str] = None
) -> dict:
    activities_str = ", ".join(activities) if activities else "family activities"

    def call_ticketmaster():
        try:
            return search_ticketmaster_events.invoke({
                "location": location, "date": date,
                "latitude": latitude, "longitude": longitude, "radius_miles": radius_miles
            })
        except Exception as e:
            return f"Ticketmaster failed: {str(e)}"

    def call_eventbrite():
        try:
            return search_eventbrite_events.invoke({
                "location": location, "query": activities_str, "date": date,
                "latitude": latitude, "longitude": longitude, "radius_miles": radius_miles
            })
        except Exception as e:
            return f"Eventbrite failed: {str(e)}"

    with ThreadPoolExecutor(max_workers=2) as executor:
        future_tm = executor.submit(call_ticketmaster)
        future_eb = executor.submit(call_eventbrite)
        ticketmaster_data = future_tm.result()
        eventbrite_data = future_eb.result()

    vibes_str = f"\nPrioritise results that are: {', '.join(vibes)}" if vibes else ""
    free_text_str = f"\nUser also searched for: \"{free_text}\"" if free_text and free_text.strip() else ""

    if latitude is not None and longitude is not None:
        radius_str = f"\nPrefer results within {radius_miles} miles of ({latitude:.4f}, {longitude:.4f}). If extending, set search_extended=true with a friendly message."
    else:
        radius_str = ""

    prompt = f"""Format this events data into JSON for a family activities finder.

Search: {activities_str} in {location}, {date}, ages {age_range}, budget {cost_range}{vibes_str}{free_text_str}{radius_str}

TICKETMASTER DATA:
{ticketmaster_data}

EVENTBRITE DATA:
{eventbrite_data}

STRICT RULES:
1. EVENT = time-specific and temporary: workshop, show, class, performance, community day. Has a specific date/time.
2. Do NOT include permanent attractions (London Eye, Madame Tussauds, Sea Life, museums) — those are venues.
3. Only include events matching: {activities_str}
4. Only use results from the data above — never add from your own knowledge
5. Return max 5 events
6. cost: NEVER use null — use "Free", "From £X", or "Paid — check website"
7. directions_url: https://www.google.com/maps/dir/?api=1&destination=ADDRESS_URL_ENCODED
8. Keywords only from: {keywords_list}
9. image_url: use the Photo URL from Ticketmaster/Eventbrite data if present, otherwise null

Return ONLY valid JSON:
{{
  "search_summary": "{activities_str} in {location}, {date}, Ages {age_range}, {cost_range}",
  "search_extended": false,
  "search_extended_message": null,
  "venues": [],
  "events": [
    {{
      "type": "event",
      "name": "name",
      "image_url": "Photo URL from data or null",
      "location": "full address",
      "latitude": 51.5074,
      "longitude": -0.1278,
      "date": "formatted date",
      "time": "10:00 AM",
      "age_range": "All ages",
      "cost": "From £18",
      "is_free": false,
      "rating": null,
      "keywords": ["indoor"],
      "description": "one sentence",
      "expanded_description": "2 sentences with practical family details",
      "booking_url": "url or null",
      "directions_url": "https://www.google.com/maps/dir/?api=1&destination=ADDRESS"
    }}
  ]
}}"""

    response = llm.invoke(prompt)
    return parse_response(response.content, activities_str, location)


# ---- LEGACY COMBINED SEARCH ----
# Kept for backward compatibility with tests
def run_agent(
    activities: list[str],
    location: str,
    date: str,
    age_range: str,
    cost_range: str,
    vibes: list[str] = [],
    latitude: Optional[float] = None,
    longitude: Optional[float] = None,
    radius_miles: int = 5,
    free_text: Optional[str] = None
) -> dict:
    with ThreadPoolExecutor(max_workers=2) as executor:
        future_venues = executor.submit(
            run_venues_search, activities, location, date, age_range,
            cost_range, vibes, latitude, longitude, radius_miles, free_text
        )
        future_events = executor.submit(
            run_events_search, activities, location, date, age_range,
            cost_range, vibes, latitude, longitude, radius_miles, free_text
        )
        venues_result = future_venues.result()
        events_result = future_events.result()

    return {
        "search_summary": venues_result.get("search_summary", f"{', '.join(activities)} in {location}"),
        "search_extended": venues_result.get("search_extended", False) or events_result.get("search_extended", False),
        "search_extended_message": venues_result.get("search_extended_message") or events_result.get("search_extended_message"),
        "venues": venues_result.get("venues", []),
        "events": events_result.get("events", []),
    }
